name: "email-rag"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/_cat/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  email_rag:
    build: .
    container_name: email-rag
    restart: on-failure:3
    depends_on:
      elasticsearch:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - ELASTIC_URL=http://elasticsearch:9200
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    networks:
      - app-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  app-network:
    driver: bridge
